### ISSUE TITLE
which link is the tool?

### ISSUE THREAD

**Issue by marcoojer** [roboticslibrary/rl#42]
Hello, i have a doubt, when doing a direct or inverse kinematics, how do you know which is the end_effector link. I saw that in the rl::mdl::Model there are a _leave and _tool member variables and when doing kinematics->getOperationalPosition(0), you do the calculus for the first _tool;. But I don't know how is the mapping between the index and the link name. How it is done?

**Comment by rickertm** [comment]
A kinematic model is represented as a tree with vertices and edges. Vertices represent intermediate frames or bodies/links. End effectors are the leaves of the tree. The tree is parsed using depth-first search and each leaf is added to the end of the `leaves` vector in the model.

In order to specify goal transformations for multiple end effectors in the inverse kinematics calculation, you can call the `rl::mdl::InverseKinematics::addGoal()` function for each end effector transform matrix and index before starting the calculation with `rl::mdl::InverseKinematics::solve()`.

**Comment by marcoojer** [comment]
Thank you very much  for answering, but how do I know the which link corresponds to each end_effector index, for example, if I have in my .urdf two "leave nodes" ```tool_0``` and ```tool_1```, how do i know which tool index correspond to each one in the ```rl::mdl::Kinematics```?

**Comment by rickertm** [comment]
The function `rl::mdl::Model::getOperationalFrame(size_t& i)` gives you access to the `rl::mdl::Frame` instead of just its transformation matrix. This class has a `getName()` function that should help you in identifying the correct leaf.

**Comment by marcoojer** [comment]
Thank you!! that solved my doubt!!
