### ISSUE TITLE
how to view urdf model 

### ISSUE THREAD

**Issue by george66s** [roboticslibrary/rl#50]
Hi, I have a robot model using urdf file format, with stl files. How can I view the model? Is there any example I can learn from?

Lots of thanks!

George

**Comment by george66s** [comment]
George again. The demo shows that .xml model with .wrl files can be viewed. Just wondering if .urdf model with .stl files can be viewed or not. Thanks!

**Comment by rickertm** [comment]
RL includes a UrdfFactory for loading kinematic models with rl::mdl since version 0.7. The current master branch also includes one for loading geometric models with rl::sg. You can use the rlCoachMdl on the master branch for viewing such a model by providing the same URDF file for both `SCENEFILE` and `MODELFILE1`:
```bash
Usage: rlCoachMdl SCENEFILE MODELFILE1 ... MODELFILEn
rlCoachMdl robot.urdf robot.urdf
```
The parsers support URDF files with basic or STL geometries and absolute or relative paths. File in xacro format first have to be converted to URDF files and paths with `package://` references have to be replaced by the actual paths, e.g.:
```diff
- <mesh filename="package://robot_description/meshes/link0.stl"/>
+ <mesh filename="../meshes/link0.stl"/>
```

**Comment by george66s** [comment]
Lots of thank. Will try and get back...

**Comment by george66s** [comment]
Here is the result. rlCoachMdl worked very well in the Clion IDE that complies the latest downloaded source in the demo sub-directory. It successfully showed the visual image of the robot model. Lots of thanks!

But it didn't work in the command line. When I typed $ rlCoachMdl Absolute_Path/my.urdf Absolute_Path/my.urdf, it returns error message: segment error (core dumped).

**Comment by george66s** [comment]
Maybe it was because my lib version was not up to 0.7?

**Comment by george66s** [comment]
I tried again. This time I went to the build sub-directory and used the rlCoachMdl built by Clion IDE in command line. It worked very well. Apparently something is wrong with my installed version of rlCoachMdl. Thanks.
